### ISSUE TITLE
Needs updating?

### ISSUE THREAD

**Issue by anicolson** [KalraA/Tachyon#5]
Hi, trying the 'Getting started' example with the latest tensorflow. Changed some of the tf functions, e.g. tf.mul -> tf.multiply, and tf.sub -> tf.subtract. Did not want to jump in to deeply into the code, was wondering if you could diagnose the error below, or update the code so that it runs with the new tf 1.0 scheme?

(tf_py2) aaron@aaron:~/my_working_directory$ python tmp.py
data/nltcs.ts.data
data/nltcs.valid.data
data/nltcs.test.data
generated a network of size 2390 with 7 layers.
Traceback (most recent call last):
  File "tmp.py", line 15, in <module>
    spn.make_random_model((prod_branch_factor, sum_branch_factor), variables, cont=False)
  File "/home/aaron/.local/lib/python2.7/site-packages/tachyon/SPN2.py", line 40, in make_random_model
    self.model.fast_compile(tensorboard_dir=tensorboard_dir)
  File "/home/aaron/.local/lib/python2.7/site-packages/tachyon/model.py", line 477, in fast_compile
    self.build_fast_forward_pass(step)
  File "/home/aaron/.local/lib/python2.7/site-packages/tachyon/model.py", line 311, in build_fast_forward_pass
    current_computation = tf.concat(1, [current_computation, input_splits[L]])
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/aaron/tf_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by friedeggs** [comment]
Hey, you could check out the commit on the development branch: b47623af04e461d80b2bf4e43016392bbed8f79d

**Comment by anicolson** [comment]
Thanks for your help, works fine.
